# flake8: noqa: E701
"""
 수작업으로 필요할때 추가하는 스텁파일
 - 독스티링 적용(독스트링은 상속이 안되기 때문에 여기서 적어야함)
    - 클래스 메소드 설명은 잘 따라옴.
"""
from __future__ import annotations
import enum
from contextlib import contextmanager
from typing import Type, Any, overload, Literal, Iterable, TypeVar, TypeGuard, Sequence
import MXSWrapperBase as mxs

_T = TypeVar('_T')
_Iter = TypeVar('_Iter', bound=Iterable)

def attime(time):...
  
def animate(on_off: bool): ...

@contextmanager
def undo(on_off: bool, name=''): ...


class runtime:
    objects: list
    selection: list
    currentTime: int
    maxfilepath: str
    maxFilePath: str
    maxfilename: str
    maxFileName: str
    animationRange: runtime.Interval
    animateMode: bool
    sliderTime: runtime.Time

    @property
    @classmethod
    def rootNode(cls) -> runtime.MAXRootNode:...

    class Value:
        def __init__(self, *args, **kwargs) -> None: ...
        @classmethod
        def getmxsprop(cls, arg1: str) -> Any:
            """ mxs 속성값을 가져옵니다.
            :param arg1: mxs 속성 이름으로 None은 에러
            """
            ...
        ...
    class MAXRootNode(Value):...


    # class Point3(Value):
    #     """[<expr>, <expr>, <expr>]

    #     [2022 api link](https://help.autodesk.com/view/MAXDEV/2022/ENU/?guid=GUID-1564BD35-50EA-4140-9150-1AECC89F713C)
    #     """
    #     x: int
    #     y: int
    #     z: int
    #     def __init__(self, *args, **kwargs) -> None: ...
    #     ...

    class Array(Sequence[_T], Value):...

    class Interval(Value):
        start: runtime.Time
        end: runtime.Time


    class BitArray(Value):
        def __iter__(self) -> runtime.BitArray: ...
        def __next__(self) -> int: ...

    class interface(Value):
        ...

    class skinUtils(interface):
        @staticmethod
        def ExtractSkinData(node) -> None: ...

        @staticmethod
        def ImportSkinData(target_node, source_node) -> None: ...

        @staticmethod
        def ImportSkinDataNoDialog(
            matchByName: bool,
            removeTargetPrefix: bool,
            removeTargetSuffix: bool,
            removeSourcePrefix: bool,
            removeSourceSuffix: bool,
            threshold: float,
            interpolationType: int
        ) -> None:
            '''
            :param matchByName: 매개 변수가 true로 설정되면 뼈가 이름으로 일치합니다(대화 상자의 Match By Name 버튼을 누르는 것과 동일). 거짓이면 뼈는 인덱스로 일치합니다.\n
                - 논쟁 2 ~ 5 개는 대화 상자의 수정 및 접미사 제거 체크 박스의 상태에 해당합니다.
            :param threshold: 임계값 인수는 대화 상자의 임계값에 해당합니다.The threshold argument corresponds to the Threshold value in the dialog. 이것은 가장 가까운 이웃 임계 값입니다.
            :param interpolationType: 마지막 인수는 `Interpolation Type` 드롭다운 목록의 선택에 해당합니다. 가능한 값은 다음과 같습니다.\n
                - 0 - Vertex에 의하여 일치\n
                -  1 - 얼굴별 경기
            '''
            ...

    class maxOps(interface):
        @staticmethod
        def getNodeByHandle(handle: int) -> runtime.node | None: ...

        @staticmethod
        def CollapseNodeTo(
            obj: runtime.GeometryClass,
            number: int,
            noWarning: bool
        ) -> runtime.node: ...

    class OkClass(Value):
        ...

    class StructDef(Value):
        ...
    class callbacks(StructDef):
        @staticmethod
        def addScript(
            arg1:runtime.Name,
            arg2:str,
            id:runtime.Name=runtime.Name('')
        ):
            """
            :param arg1: 콜벡타입이름
            :param arg2: 실행 코드 문자열
            """;...
        @staticmethod
        def show(arg1:runtime.Name, asArray:bool=False) -> list[list]|None:
            """
            :param arg1: 콜백타입이름
            :param asArray: 콜백함수들을 배열로 반환할지 여부, 아니면 리스터 창에 출력만함
            :return: 콜백함수들 정보
                #(#(#filePreOpen, #PhysXPlugin, false, false, "px_filePreOpen()", false),
            """
            ...
        @staticmethod
        def notificationParam(*args, **kwargs):
            ...
        @staticmethod
        def removeScripts(id:runtime.Name|None=None):
            """ 콜백함수 제거 """
            ...
        @staticmethod
        def broadcastCallback(*args, **kwargs):
            ...
    class custAttributes(StructDef):
        @staticmethod
        def unRegisterDefLoadCallback(*args, **kwargs):
            ...
        @staticmethod
        def getDef(*args, **kwargs):
            ...
        @staticmethod
        def delete(*args, **kwargs):
            ...
        @staticmethod
        def getDefClass(*args, **kwargs):
            ...
        @staticmethod
        def unRegisterAllDefLoadCallbacks(*args, **kwargs):
            ...
        @staticmethod
        def getDefSource(*args, **kwargs):
            ...
        @staticmethod
        def getDefInstances(*args, **kwargs):
            ...
        @staticmethod
        def getDefData(*args, **kwargs):
            ...
        @staticmethod
        def get(*args, **kwargs):
            ...
        @staticmethod
        def getSceneLoadVersionHandlingBehavior(*args, **kwargs):
            ...
        @staticmethod
        def setDefData(*args, **kwargs):
            ...
        @staticmethod
        def setSceneLoadVersionHandlingBehavior(*args, **kwargs):
            ...
        @staticmethod
        def redefine(*args, **kwargs):
            ...
        @staticmethod
        def getPBlockDefs(*args, **kwargs):
            ...
        @staticmethod
        def getSceneMergeVersionHandlingBehavior(*args, **kwargs):
            ...
        @staticmethod
        def getSceneDefs(*args, **kwargs):
            ...
        @staticmethod
        def setSceneMergeVersionHandlingBehavior(*args, **kwargs):
            ...
        @staticmethod
        def deleteDef(*args, **kwargs):
            ...
        @staticmethod
        def setLimits(*args, **kwargs):
            ...
        @staticmethod
        def showRegisteredDefLoadCallbacks(*args, **kwargs):
            ...
        @staticmethod
        def getDefs(*args, **kwargs):
            ...
        @staticmethod
        def add(*args, **kwargs):
            ...
        @staticmethod
        def registerDefLoadCallback(*args, **kwargs):
            ...
        @staticmethod
        def makeUnique(*args, **kwargs):
            ...
        @staticmethod
        def getOwner(*args, **kwargs):
            ...
        @staticmethod
        def count(*args, **kwargs):
            ...
    class pluginPaths(StructDef):
        @staticmethod
        def count() -> int:
            ...
        @staticmethod
        def get(*args, **kwargs):
            ...
    class pathConfig(StructDef):
        xrefPaths: 'Any'  # systemGlobal
        @staticmethod
        def doesFileExist(*args, **kwargs) -> bool:
            ...
        @staticmethod
        def removePathLeaf(*args, **kwargs):
            ...
        @staticmethod
        def doSetProjectFolderSteps(*args, **kwargs):
            ...
        @staticmethod
        def SaveTo(*args, **kwargs):
            ...
        @staticmethod
        def isUncSharePath(*args, **kwargs):
            ...
        @staticmethod
        def getProjectSubDirectoryCount(*args, **kwargs):
            ...
        @staticmethod
        def resolvePathSymbols(*args, **kwargs):
            ...
        @staticmethod
        def doSetProjectFolderStepsUsingDirectory(*args, **kwargs):
            ...
        @staticmethod
        def isPathRootedAtBackslash(*args, **kwargs):
            ...
        @staticmethod
        def getProjectSubDirectory(*args, **kwargs):
            ...
        @staticmethod
        def normalizePath(*args, **kwargs):
            ...
        @staticmethod
        def isProjectFolder(*args, **kwargs) -> bool:
            ...
        mapPaths: 'Any'  # systemGlobal
        @staticmethod
        def isPathRootedAtDriveLetter(*args, **kwargs):
            ...
        @staticmethod
        def addProjectDirectoryCreateFilter(*args, **kwargs):
            ...
        @staticmethod
        def convertPathToLowerCase(*args, **kwargs):
            ...
        @staticmethod
        def getProjectFolderPath(*args, **kwargs):
            ...
        @staticmethod
        def pathsResolveEquivalent(*args, **kwargs):
            ...
        @staticmethod
        def removeProjectDirectoryCreateFilter(*args, **kwargs):
            ...
        @staticmethod
        def convertPathToRelativeTo(*args, **kwargs):
            ...
        @staticmethod
        def getCurrentProjectFolderPath(*args, **kwargs):
            ...
        pluginPaths: runtime.pluginPaths
        @staticmethod
        def load(*args, **kwargs):
            ...
        @staticmethod
        def appendPath(*args, **kwargs) -> str:
            ...
        @staticmethod
        def removeAllProjectDirectoryCreateFilters(*args, **kwargs):
            ...
        @staticmethod
        def convertPathToUnc(*args, **kwargs):
            ...
        @staticmethod
        def isAbsolutePath(*args, **kwargs):
            ...
        @staticmethod
        def SetDir(*args, **kwargs):
            ...
        @staticmethod
        def GetDir(*args, **kwargs):
            ...
        @staticmethod
        def stripPathToTopParent(*args, **kwargs):
            ...
        @staticmethod
        def getProjectDirectoryCreateFilters(*args, **kwargs):
            ...
        @staticmethod
        def convertPathToAbsolute(*args, **kwargs):
            ...
        @staticmethod
        def isLegalPath(*args, **kwargs):
            ...
        resolveUNC: 'Any'  # systemGlobal
        @staticmethod
        def merge(*args, **kwargs):
            ...
        @staticmethod
        def removePathTopParent(*args, **kwargs):
            ...
        @staticmethod
        def doProjectSetupSteps(*args, **kwargs):
            ...
        sessionPaths: 'Any'  # systemGlobal
        @staticmethod
        def isUsingProfileDirectories(*args, **kwargs):
            ...
        @staticmethod
        def isRootPath(*args, **kwargs):
            ...
        @staticmethod
        def getCurrentProjectFolder(*args, **kwargs):
            ...
        @staticmethod
        def stripPathToLeaf(*args, **kwargs):
            ...
        @staticmethod
        def doProjectSetupStepsUsingDirectory(*args, **kwargs):
            ...
        @staticmethod
        def isUsingRoamingProfiles(*args, **kwargs):
            ...
        @staticmethod
        def isUncPath(*args, **kwargs):
            ...
        @staticmethod
        def setCurrentProjectFolder(*args, **kwargs):
            ...
    class modPanel(StructDef):
        @staticmethod
        def addModToSelection(*args, **kwargs): ...
        @staticmethod
        def isPinStackEnabled(*args, **kwargs): ...
        @staticmethod
        def setPinStack(*args, **kwargs): ...
        @staticmethod
        def getPinStack(*args, **kwargs): ...
        @staticmethod
        def validModifier(*args, **kwargs) -> bool: ...
        @staticmethod
        def setCurrentObject(modifier: runtime.modifier) -> bool: ...
        @staticmethod
        def getCurrentObject() -> runtime.modifier: ...

        @staticmethod
        def getModifierIndex(
            obj: runtime.node, modifier: runtime.modifier
        ) -> int:
            '''
            :return: 최상단 상단 스택이 1로 부터 시작하는 위치숫자
            - 위치숫자1 == obj.modifiers[0]
            '''
            ...

    class refs(StructDef):
        @staticmethod
        def dependentNodes(*args, **kwargs) -> list: ...

    class skinOps(StructDef):
        '''
        - <https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=GUID-0820AA26-920F-434D-A6BC-E8B6B57F54AC>  # noqa: E501
        '''
        @staticmethod
        def GetBoneNode(skin, bone_index:int) -> runtime.GeometryClass: ...
        @staticmethod
        def GetNumberBones(skin) -> int: ...
        @staticmethod
        def GetListIDByBoneID(skin, bone_id: int) -> int: ...
        @staticmethod
        def GetBoneIDByListID(skin, list_id: int) -> int: ...
        @staticmethod
        def GetBoneNodes(skin) -> list: ...
        @staticmethod
        def GetBoneName(skin, bone_index: int, nameflag: Literal[0,1]) -> str:
            '''
            :param nameflag:
                - 0: bone name\n
                - 1: UI list name
            :type nameflag: Literal[0,1]
            '''
            ...

        @overload
        @staticmethod
        def ReplaceVertexWeights(
            Skin: Any,
            vertex_integer: int,
            vertex_bone_integer: int,
            weight_float: float,
            node: runtime.node|None=None, name: str=""): ...

        @overload
        @staticmethod
        def ReplaceVertexWeights(
            Skin: Any,
            vertex_integer: int,
            vertex_bone_array: runtime.Array|list,
            weight_array: runtime.Array|list,
            node: runtime.node|None=None,
            name: str=""): ...

        @staticmethod
        def GetVertexWeight(
            skin,
            vertex_integer,
            vertex_bone_integer
        ) -> float:
            ...

        @staticmethod
        def GetVertexWeightBoneID(
            skin,
            vertex_integer,
            vertex_bone_intger
        ) -> int:
            '''
            skin 의 vertex_integer번째 정점의 vertex_bone_intger번째 본의 ID를 반환합니다.
            '''
            ...

        @staticmethod
        def GetVertexWeightCount(skin: runtime.modifier, vert_number: int)-> int: ...
        @staticmethod
        def AddBone(*args, **kwargs): ...
        @staticmethod
        def RemoveBone(*args, **kwargs):
            '''
            - `skinOps.removebone <Skin>`
            - `skinOps.removebone <Skin> <BoneID_integer> [(node:<node> | name:<string>)]`
            '''
            ...
    class windows:
        @staticmethod
        def getMAXHWND() -> int: ...
    class Name(runtime.Value):
        def __init__(self, string):
            ...
    class Primitive(runtime.Value):
        '''
        매소드임
        - https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=Max_Developer_Help_cpp_ref_class_primitive_html
        - https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=GUID-B28D7100-1F5F-4A0F-BFA3-17ABADD13580
            - Primitives클래스에 국한되지 않는 메서드입니다. 이 메서드는 인수의 타입(있는 경우)을 확인하고, 타입이 올바르지 않으면 오류를 발생시킵니다. Primitive의 정의는 하나뿐입니다.
        '''
        ...
    class Interface(runtime.Value): ...
    class menuMan(Interface):
        @staticmethod
        def loadMenuFile(file:str) -> bool:
            """
            :param file: filename
            """
            ...
        @staticmethod
        def saveMenuFile(file:str) -> bool:
            """
            :param file: filename
            """
            ...
        @staticmethod
        def getMenuFile() -> str:
            """
            :return: filename
            """
            ...
        @staticmethod
        def updateMenuBar() -> None: ...
        @staticmethod
        def registerMenuContext(contextId: int) -> bool: ...
        @staticmethod
        def findMenu(menuName:str) -> runtime.MixinInterface.menu: ...
        @staticmethod
        def findQuadMenu(menuName:str) -> runtime.MixinInterface.menu: ...
        @staticmethod
        def unRegisterMenu(menu:runtime.MixinInterface.menu) -> bool: ...
        @staticmethod
        def unRegisterQuadMenu(menu:runtime.MixinInterface.quadMenu) -> bool: ...
        @staticmethod
        def createMenu(name:str) -> runtime.MixinInterface.menu: ...
        @staticmethod
        def createQuadMenu(name:str, quad1Name:str, quad2Name:str, quad3Name:str, quad4Name:str) -> runtime.MixinInterface.quadMenu: ...
        @staticmethod
        def createSubMenuItem(name:str, subMenu:runtime.MixinInterface.menu) -> runtime.MixinInterface.menuItem:
            """
            :param name: 메뉴 이름
            :param subMenu: 생성될 메뉴
            :return: 생성된 아이템
            """
            ...
        @staticmethod
        def createSeparatorItem() -> runtime.MixinInterface.menuItem: ...
        @staticmethod
        def createActionItem(macroScriptName:str, macroScriptCategory:str) -> runtime.MixinInterface.menuItem: ...
        @staticmethod
        def setViewportRightClickMenu(which: runtime.Name, menu) -> bool:
            """
            :param which: which enums: {#nonePressed|#shiftPressed|#altPressed|#controlPressed|#shiftAndAltPressed|#shiftAndControlPressed|#controlAndAltPressed|#shiftAndAltAndControlPressed}
            """
            ...
        @staticmethod
        def getViewportRightClickMenu(which: runtime.Name):
            """
            :param which: which enums: {#nonePressed|#shiftPressed|#altPressed|#controlPressed|#shiftAndAltPressed|#shiftAndControlPressed|#controlAndAltPressed|#shiftAndAltAndControlPressed}
            :return: runtime.MixinInterface.menu
            """
            ...
        @staticmethod
        def getMainMenuBar() -> runtime.MixinInterface.menu: ...
        @staticmethod
        def getMainMsetMainMenuBarenuBar(menu:runtime.MixinInterface.menu) -> bool: ...
        @staticmethod
        def getShowAllQuads(quadMenu:runtime.MixinInterface.quadMenu) -> bool: ...
        @staticmethod
        def setShowAllQuads(quadMenu:runtime.MixinInterface.quadMenu, value:bool) -> None: ...
        @staticmethod
        def getQuadMenuName(quadMenu:runtime.MixinInterface.quadMenu) -> str: ...
        @staticmethod
        def setQuadMenuName(quadMenu:runtime.MixinInterface.quadMenu, name:str) -> None: ...
        @staticmethod
        def numMenus() -> int: ...
        @staticmethod
        def getMenu(index: int) -> runtime.MixinInterface.menu:
            """:param index: 메뉴 인덱스 (1부터 시작)""";...
        @staticmethod
        def numQuadMenus() -> int: ...
        @staticmethod
        def getQuadMenu(index: int) -> runtime.MixinInterface.quadMenu:
            """:param index: 메뉴 인덱스 (1부터 시작)""";...
        @staticmethod
        def createMenuItemFromAction(group:str, action: str, categroy:str|None=None) -> runtime.MixinInterface.menuItem: ...
    
    class MixinInterface(Value):
        """ 타입 체킹용 클래스로 하위클래스를 직접 사용금지 """
        class menu(runtime.Interface):
            def setTitle(self, title:str) -> None: ...
            def getTitle(self) -> str: ...
            def numItems(self) -> int: ...
            def getItem(self, position: int) -> runtime.MixinInterface.menu:
                """:param position: 메뉴 아이템 위치 (1부터 시작)""";...
            def addItem(self, item: runtime.MixinInterface.menu, position: int) -> None:
                """:param position: 1부터 시작""";...
            def removeItemByPosition(self, position: int) -> None: ...
            def removeItem(self, item: runtime.MixinInterface.menu) -> None:
                """ 메뉴에서 item을 제거 것(삭제 아님)""";...

        class menuItem(runtime.Interface):
            def setTitle(self, title:str) -> None: ...
            def getTitle(self) -> str: ...
            def setUseCustomTitle(self, value:bool) -> bool: ...
            def getUseCustomTitle(self) -> str: ...
            def setDisplayFlat(self, value:bool) -> bool: ...
            def getDisplayFlat(self) -> bool: ...
            def getIsSeparator(self) -> bool: ...
            def getSubMenu(self) -> runtime.MixinInterface.menu: ...

        class quadMenu(runtime.Interface):
            def getMenu(self, position:int) -> runtime.MixinInterface.menu: ...
            def trackMenu(self, showAllQuads:bool) -> None: ...

    class list(MixinInterface):
        """ https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=Max_Developer_Help_cpp_ref_class_i_list_control_html"""
        count: int
        def getCount(self) -> int: ...
        def setActive(self, arg1: int) -> None:
            """:param arg1: 1부터 시작, 활성화할 대상""";...
        def getActive(self) -> int:
            """:retrun: 활성화 인덱스 1 부터""";...
        def delete(self, arg1: int) -> None:
            """:param arg1: 1부터 시작, 삭제할 대상""";...
        def cut(self, arg1: int) -> None:...
        def paste(self, arg1: int) -> None:...
        def getName(self, arg1: int) -> str:...
        def setName(self, arg1: int, arg2:str) -> None:
            """
            :param arg1: <index>listIndex: 항목의 인덱스입니다.
            :param arg2:  <string>name: 설정할 이름입니다.""";...
    class constraints(MixinInterface):
            def getNumTargets(self) -> int: ...
            def getNode(self, nodeNumber: int) -> runtime.node: ...
            def getWeight(self, targetNumber: int) -> float: ...
            def setWeight(self, targetNumber: int, weight: float) -> bool: ...
            def appendTarget(self, target:runtime.node, weight:float) -> bool: ...
            def deleteTarget(self, targetNumber: int) -> bool: ...

    class macros(StructDef):

        @staticmethod
        def new(*args, **kwargs) -> None: ...

    @staticmethod
    def append(*args):
        ''' '''
        ...
    @staticmethod
    def completeRedraw() -> bool:
        ''' 화면 강재 갱신(씬 번경 업데이트시)'''
        ...
    @staticmethod
    def isValidObj(*args, **kwargs) -> bool:
        ''' 오브젝트 유효성 검사'''
        ...
    @staticmethod
    def rotateYPRMatrix(yaw: int|float, pitch: int|float, roll: int|float) -> runtime.Matrix3:
        '''
        parems:
        - yaw: int|float - y축
        - pitch: int|float - x축
        - roll: int|float - z축
        '''
        ...
    @staticmethod
    def preRotateX(matrix3: runtime.Matrix3, number: int|float) -> runtime.Matrix3: ...
    ''' maxtrix3는 참조값으로 업데이트됨, number는 회전값 '''
    @staticmethod
    def preRotateY(matrix3: runtime.Matrix3, number: int|float) -> runtime.Matrix3: ...
    ''' maxtrix3는 참조값으로 업데이트됨, number는 회전값 '''
    @staticmethod
    def preRotateZ(matrix3: runtime.Matrix3, number: int|float) -> runtime.Matrix3: ...
    ''' maxtrix3는 참조값으로 업데이트됨, number는 회전값 '''
    @staticmethod
    def delete(*args, **kwargs) -> Any: ...
    @staticmethod
    def isKindOf(arg1: Any, arg2:Type[_T]) -> TypeGuard[_T]: ...
    @staticmethod
    def messageBox(*args, **kwargs) -> Any: ...
    @staticmethod
    def attachObjects(*args, **kwargs) -> Any: ...
    @staticmethod
    def quat(*args, **kwargs) -> Any: ...
    @staticmethod
    def getPropertyController(*args, **kwargs) -> Any: ...
    @staticmethod
    def hide(*args, **kwargs) -> Any: ...
    @staticmethod
    def setProperty(*args, **kwargs) -> Any: ...
    @staticmethod
    def getProperty(*args, **kwargs) -> Any: ...
    @staticmethod
    def getClassInstances(*args, **kwargs) -> type: ...
    @staticmethod
    def classof(*args, **kwargs) -> type: ...
    @staticmethod
    def cross(*args, **kwargs) -> None: ...
    @staticmethod
    def normalize(transform: Point3) -> Point3: ...
    @staticmethod
    def distance(a: Point3, b: Point3) -> float: ...
    @staticmethod
    def getCurrentSelection() -> Array: ...
    @staticmethod
    def isValidNode(obj: _T|None) -> TypeGuard[_T]: ...
    @staticmethod
    def GetNamedSelSetName(i: int) -> str:
        """ n번째 명명된 선택 세트의 이름을 반환합니다. """
        ...
    @staticmethod
    def GetNamedSelSetItem(i: int, n: int) -> mxs.Node:
        """ 특정 명명된 선택 세트에서 의 포인터를 검색합니다.INode """
        ...
    @staticmethod
    def GetNumNamedSelSets() -> int:
        """ 명명된 선택 세트의 수를 반환합니다. """
        ...
    @staticmethod
    def GetNamedSelSetItemCount(i: int) -> int:
        """ 명명된 선택 세트의 항목 수를 반환합니다. """
        ...
    @staticmethod
    def getNodeByName(name: str) -> mxs.Node: ...
    @staticmethod
    def setUserPropVal (
        arg1, arg2:str, arg3:str|int|bool,
        quoteString:bool=False, encodeCRLF: bool=False
    ) -> None:
        r"""
        :param arg1: 노드
        :param arg2: 키 문자열
        :param arg3: 입력할 값
        :param quoteString: 값을 문자열로 저장할지 여부
        :param encodeCRLF:   encodeCRLF가 지정되지 않았거나 true로 지정된 경우
            속성 값의 문자열에 있는 캐리지 리턴 또는 줄 바꿈 문자는 16진수
            표현으로 변환되고, 그렇지 않으면 16진수 표현으로 변환되지 않습니다.
            즉, '\r\n'은 '\xd\xa'로 변환됩니다.
        """;...
    @staticmethod
    def getUserPropVal(obj, key_string, *args, **kwargs) -> str: ...
    @staticmethod
    def ShellLaunch(*args, **kwargs) -> None: ...
    @staticmethod
    def saveMaxFile(*args, **kwargs) -> None: ...
    @staticmethod
    def getFiles(*args, **kwargs) -> list: ...
    @staticmethod
    def getFilenameType(*args, **kwargs) -> str: ...
    @staticmethod
    def getFilenameFile(*args, **kwargs) -> str: ...
    @staticmethod
    def filenameFromPath(*args, **kwargs) -> str: ...
    @staticmethod
    def getFilenamePath(*args, **kwargs) -> str: ...
    @staticmethod
    def GetDir(name: runtime.Name) -> str:
        """:param name: #userMacros 같은 예약어 네임 """;...
    @staticmethod
    def resetMaxFile(noPrompt: runtime.Name) -> None: ...
    @staticmethod
    def clearListener() -> None: ...
    @staticmethod
    def copy(arg1: _T) -> _T: ...


    class Object(Value):...
    class MAXObject(Value):...
    class Time(Value, int, float):
        frame: float
        def __init__(self, *args, **kwargs) -> None: ...
    class rotationController(MAXWrapper): ...
    class Euler_XYZ(rotationController): ...
    class tcb_rotation(rotationController): ...
    class rotation_list(runtime.list, rotationController):
        available: runtime.Quat
        average: bool
        weight: runtime.Array[float]
        list: runtime.list
    class Orientation_Constraint(constraints, rotationController):
        ...
    class positionController(MAXWrapper):
        """ """;...
    class Position_Constraint(constraints, positionController): ...
    class position_list(positionController):
        weight: runtime.Array[float]
        average: bool
        index: int
        indexMode: bool
        count: int
        active: int
        """ index"""
        Available : runtime.Point3
        
        def getCount(self) -> int:...
        def setActive(self, arg1: int) -> None:...

    class Position_XYZ(MAXWrapper): ...
    class Matrix3Controller(MAXWrapper): ...
    class prs(Matrix3Controller): ...
    class transform_script(Matrix3Controller):
        class Type(enum.Enum):
            unknown = runtime.Name("unknown")
            target = runtime.Name("target")
            constant = runtime.Name("constant")
            object = runtime.Name("object")
            node = runtime.Name("node")
        ThrowOnError: bool
        def __init__(self, *args, **kwargs) -> None: ...
        def AddConstant(self, *args, **kwargs) -> bool: ...
        def SetConstant(self, which: str|int, *args, **kwargs) -> bool: ...
        def GetConstant(self, which: str|int, *args, **kwargs) -> Any: ...
        def AddTarget(
                self,
                value_name:str,
                target: runtime.node,
                Offset:int|float = runtime.Time(0),
                Owner:Any=None) -> bool: ...
        def SetTarget(self, which: str|int, target:runtime.Value, Owner:runtime.Value|None=None) -> bool: ...
        def GetTarget(self, which: str|int, asObject:bool=False) -> runtime.Value: ...
        # ObjectVariable
        def AddObject(self, *args, **kwargs) -> bool: ...
        def SetObject(self, which: str|int, object:runtime.Object) -> bool: ...
        def GetObject(self, which: str|int) -> runtime.MAXObject: ...
        def AddNode(self, name:str, node: runtime.node) -> bool: ...
        def SetNode(self, which: str|int, node: runtime.node) -> bool: ...
        def GetNode(self, which: str|int) -> runtime.node: ...
        def DeleteVariable(self, which: str|int) -> bool: ...
        # General Variable Access
        def NumVariables(self) -> int: ...
        def VariableExists(self, *args, **kwargs) -> bool: ...
        def GetType(self, *args, **kwargs) -> runtime.transform_script.Type: ...
        def GetName(self, *args, **kwargs) -> str: ...
        def RenameVariable(self, *args, **kwargs) -> bool: ...
        def GetIndex(self, name:str) -> int: ...
        def GetValue(self, *args, asObject:bool=False, **kwargs) -> runtime.Value: ...
        def GetVarValue(self, *args, **kwargs) -> runtime.Value: ...
        # Variable Time Offset
        def SetOffset(self, which: str|int, offset:runtime.Time, *args, **kwargs) -> bool: ...
        def GetOffset(self, which: str|int, *args, **kwargs) -> runtime.Time: ...
        ...
        def SetExpression(self, expression:str) -> bool: ...

    class Vertical_Horizontal_Turn(MAXWrapper): ...
    
    class GeometryClass(node):
        name: str
        transform: runtime.Matrix3
        mesh: runtime.TriMesh
        numfaces: int
        wireColor: runtime.Color
        modifiers: dict[runtime.Name|int, runtime.modifier]|list[runtime.modifier]
        def __init__(self, name:str, **kwargs) -> None: ...
        ...
    class Dummy(GeometryClass): ...
    class Point(GeometryClass): ...
    class Biped_Object(GeometryClass): ...

    class logsystem(StructDef):
        logDays: int
        logSize: int
        quietMode: bool
        enabled: bool
        longevity: runtime.Name
        ''' Literal[#days] '''
        @staticmethod
        def loadState(*args, **kwargs) -> None: ...
        @staticmethod
        def getLogName(*args, **kwargs) -> str: ...
        @staticmethod
        def setLogLevel(*args, **kwargs) -> None: ...
        @staticmethod
        def getLogLevel(*args, **kwargs) -> None: ...
        @staticmethod
        def getNetLogFileName() -> str: ...
        @staticmethod
        def logEntry(*args, **kwargs) -> None: ...
        @staticmethod
        def logName(*args, **kwargs) -> None: ...
        @staticmethod
        def saveState(*args, **kwargs) -> None: ...

    class helper(node): ...

    class Bone(helper):
        """
        :ivar boneScaleType: runtime.Name('none')
        """
        length: int
        fronfin: bool
        frontfinsize: int
        sidefins: bool
        sidefinssize: int
        boneEnable: bool
        boneFreeaeLength: bool
        boneAutoAlign: bool
        boneScaleType: runtime.Name
        def __init__(self, *args, **kwargs) -> None:
            ...
        
    class vertexColorType(mxs.Name):
        color: Type[mxs.Name]
        illum: Type[mxs.Name]
        alpha: Type[mxs.Name]
        color_plus_illum: Type[mxs.Name]
        ...
    class NodeGeneric(Value): ...
    class setFaceSelection(NodeGeneric):
        def __new__(cls, *args, **kwargs) -> None: ...
    class getFaceSelection(NodeGeneric):
        def __new__(cls, *args, **kwargs) -> runtime.BitArray: ...
    class getUserProp(NodeGeneric):
        """
        :param arg1: 값을 가져올 노드 
        :type arg1: runtime.node
        :param arg2: key용 문자열
        :type arg2: str
        :return: 값을 int, bool, str 중 하나로 반환합니다. 없으면 None.
        :rtype: int | bool | str | None
        """
        def __new__(cls, arg1, arg2:str) -> int|bool|str|None: ...
    class setUserProp(NodeGeneric):
        """
        :param arg1: 값을 가져올 노드 
        :type arg1: runtime.node
        :param arg2: key용 문자열
        :type arg2: str
        :return: 값을 int, bool, str 중 하나로 반환합니다. 없으면 None.
        :rtype: int | bool | str | None
        """
        def __new__(cls, arg1, arg2:str, arg3:int|bool|str) -> int|bool|str|None: ...
    class MAXWrapper(runtime.Value):
        '''
        https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=GUID-025B6C97-8601-4FEF-ACB8-E47EE0929300
        '''
        category: runtime.Name
        categories: runtime.Array
        classes: runtime.Array
        classID: runtime.Array
        creatabl: bool
        localizedName: str
        ''' 읽기 전용'''
        nonLocalizedNam: str
        ''' 읽기 전용'''
        dllName: str
        ''' 읽기 전용'''
        dllIsLoaded: bool
        ''' 2012이상 - 읽기 전용'''
        isMSPluginClass: bool
        ''' 2012이상 - 읽기 전용'''
        ...
    class FaceSelection(Value): ...
    class node(runtime.MAXWrapper):
        """[Node : MAXWrapper](https://help.autodesk.com/view/MAXDEV/2023/ENU/?guid=GUID-1C9953AA-4750-4147-91DC-127AF2F7BC87)
        [Interface : INode](https://help.autodesk.com/view/MAXDEV/2023/ENU/?guid=GUID-0BFEF796-5952-48B0-8929-88475F927649)
        """
        name: str
        transform: runtime.Matrix3
        handle: int
        baseObject: runtime.node
        '''
        - [`<node>`.baseObject  A subclass of Node  default: varies](https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=GUID-00AB0CFA-3190-4A28-A185-4774B684F6D8)
        - The baseObject속성은 수정자 스택의 기본 개체에 대한 액세스를 제공합니다. 왜냐하면 classOf()장면 노드 객체의 함수는 세계 상태 객체(스택의 상단)의 클래스를 반환합니다. baseObject노드를 만드는 데 사용되는 원래 개체의 클래스를 결정하는 속성. 
        '''
        material: runtime.Material|None
        parent: runtime.node|None
        children: runtime.Array
        mesh: runtime.TriMesh
        boundingBox: runtime.Box3
        displayByLayer: bool
        motionByLayer: bool
        renderByLayer: bool
        colorByLayer: bool
        globalIlluminationByLayer: bool
        isTarget: bool
        lookAt: runtime.node|None
        target: runtime.node|None
        targetDistance: float
        isHidden: bool
        isNodeHidden: bool
        isHiddenInVpt: bool
        isFrozen: bool
        isNodeFrozen: bool
        isSelected: bool
        xray: bool
        boxMode: bool
        allEdges: bool
        vertexTicks: bool
        """ 노드의 모든 정점을 뷰포트에 눈금으로 표시할지 여부를 가져오거나 설정합니다. """
        backFaceCull: bool
        showTrajectory: bool
        ignoreExtents: bool
        showFrozenInGray: bool
        wireColor: runtime.Color
        """  """
        showLinks: bool
        showLinksOnly: bool
        showVertexColors: bool
        vertexColorType: runtime.Name
        vertexColorsShaded: bool
        isDependent: bool
        visibility: bool
        controller: runtime.Matrix3Controller
        renderable: bool
        inheritVisibility: bool
        primaryVisibility: bool
        secondaryVisibility: bool
        receiveShadows: bool
        castShadows: bool
        applyAtmospherics: bool
        renderOccluded: bool
        gbufferChannels: bool
        imageMotionBlurMultiplier: float
        motionBlurOn: bool
        motionBlurOnController: runtime.floatController
        motionBlur: runtime.Name
        ''' default: #none
        :rtype: Literal["#none", "#object", "#image"]
        '''
        generatecaustics: bool
        rcvcaustics: bool
        generateGlobalIllume: bool
        rcvGlobalIllum: bool
        ...
    class floatController(MAXWrapper):...
    class Editable_mesh(GeometryClass):...
    class Editable_Poly(GeometryClass):...
    class PolyMeshObject(GeometryClass):...

    class biped(runtime.StructDef):
        @staticmethod
        def createXtraOpposite(*args, **kwargs): ...
        @staticmethod
        def numTwistPoses(*args, **kwargs): ...
        @staticmethod
        def getParentNodePos(*args, **kwargs): ...
        @staticmethod
        def getIKActive(*args, **kwargs): ...
        @staticmethod
        def setCopyName(*args, **kwargs): ...
        @staticmethod
        def getClipAtTime(*args, **kwargs): ...
        @staticmethod
        def numLayers(*args, **kwargs): ...
        @staticmethod
        def saveTalentPoseFile(*args, **kwargs): ...
        @staticmethod
        def saveBipFileDlg(*args, **kwargs): ...
        @staticmethod
        def getTwistPoseTwist(*args, **kwargs): ...
        @staticmethod
        def clearAllAnimation(*args, **kwargs): ...
        @staticmethod
        def scaleFootprints(*args, **kwargs): ...
        @staticmethod
        def copyBipPose(*args, **kwargs): ...
        @staticmethod
        def collapsePosSubAnims(*args, **kwargs): ...
        @staticmethod
        def clearPrefClips(*args, **kwargs): ...
        @staticmethod
        def setCurrentLayer(*args, **kwargs): ...
        @staticmethod
        def getTwistStartId(*args, **kwargs): ...
        @staticmethod
        def saveStpFile(*args, **kwargs): ...
        @staticmethod
        def addNewKey(*args, **kwargs): ...
        @staticmethod
        def getXtraOpposite(*args, **kwargs): ...
        @staticmethod
        def createTwistPose(*args, **kwargs): ...
        @staticmethod
        def getClavicleVals(*args, **kwargs): ...
        @staticmethod
        def setKey(*args, **kwargs): ...
        @staticmethod
        def loadCopyPasteFile(*args, **kwargs): ...
        @staticmethod
        def createPosSubAnims(*args, **kwargs): ...
        @staticmethod
        def createLayer(*args, **kwargs): ...
        @staticmethod
        def multipleFSDlg(*args, **kwargs): ...
        @staticmethod
        def loadBipFile(*args, **kwargs): ...
        @staticmethod
        def getTwistPoseBias(*args, **kwargs): ...
        @staticmethod
        def clearSelectedAnimation(*args, **kwargs): ...
        @staticmethod
        def convertFromBuffer(*args, **kwargs): ...
        @staticmethod
        def copyBipTrack(*args, **kwargs): ...
        @staticmethod
        def collapseRotSubAnims(*args, **kwargs): ...
        @staticmethod
        def addPrefClip(*args, **kwargs): ...
        @staticmethod
        def getLimbRetargetState(*args, **kwargs): ...
        @staticmethod
        def maxTwistNodes(*args, **kwargs): ...
        @staticmethod
        def saveBipedAnimationLayer(*args, **kwargs): ...
        @staticmethod
        def createNew(*args, **kwargs): ...
        @staticmethod
        def deleteXtra(*args, **kwargs): ...
        @staticmethod
        def setTwistPose(*args, **kwargs): ...
        @staticmethod
        def getHingeVal(*args, **kwargs): ...
        @staticmethod
        def setSelectedKey(*args, **kwargs): ...
        @staticmethod
        def saveCopyPasteFile(*args, **kwargs): ...
        @staticmethod
        def createRotSubAnims(*args, **kwargs): ...
        @staticmethod
        def deleteLayer(*args, **kwargs): ...
        @staticmethod
        def addFootprint(*args, **kwargs): ...
        @staticmethod
        def loadStpFile(*args, **kwargs): ...
        @staticmethod
        def getXtraName(*args, **kwargs): ...
        @staticmethod
        def getEulerActive(*args, **kwargs): ...
        @staticmethod
        def mirror(*args, **kwargs): ...
        @staticmethod
        def pasteFromBuffer(*args, **kwargs): ...
        @staticmethod
        def pasteBipPosture(*args, **kwargs): ...
        @staticmethod
        def copyPosture(*args, **kwargs): ...
        @staticmethod
        def deletePrefClip(*args, **kwargs): ...
        @staticmethod
        def setTransform(
            obj: runtime.Biped_Object,
            target: runtime.Name,
            value: runtime.Point3|runtime.Quat,
            set_key: bool,
            limb: runtime.Biped_Object|None = None,
        ): ...
        @staticmethod
        def getTransform(
            obj: runtime.Biped_Object,
            target: runtime.Name,
            limb: runtime.Biped_Object|None = None,
        ): ...
        @staticmethod
        def setLimbRetargetState(*args, **kwargs): ...
        @staticmethod
        def maxTwistLinks(*args, **kwargs): ...
        @staticmethod
        def saveBipedBaseAnimationLayer(*args, **kwargs): ...
        @staticmethod
        def deleteKeys(*args, **kwargs): ...
        @staticmethod
        def attachXtra(*args, **kwargs): ...
        @staticmethod
        def deleteTwistPose(*args, **kwargs): ...
        @staticmethod
        def getHorseAnkleVal(*args, **kwargs): ...
        @staticmethod
        def setPlantedKey(*args, **kwargs): ...
        @staticmethod
        def numCopyCollections(*args, **kwargs): ...
        @staticmethod
        def createScaleSubAnims(*args, **kwargs): ...
        @staticmethod
        def collapseAtLayer(*args, **kwargs): ...
        @staticmethod
        def addMultipleFootprints(*args, **kwargs): ...
        @staticmethod
        def loadFigFile(*args, **kwargs): ...
        @staticmethod
        def getEulerOrder(*args, **kwargs): ...
        @staticmethod
        def mirrorInPlace(*args, **kwargs): ...
        @staticmethod
        def getCurrentRange(*args, **kwargs): ...
        @staticmethod
        def pasteBipPose(*args, **kwargs): ...
        @staticmethod
        def pastePosture(*args, **kwargs): ...
        @staticmethod
        def isPrefClip(*args, **kwargs): ...
        @staticmethod
        def getRetargetRefBip(*args, **kwargs): ...
        @staticmethod
        def setMultipleKeys(*args, **kwargs): ...
        @staticmethod
        def loadBipedAnimationLayer(*args, **kwargs): ...
        @staticmethod
        def selectKeys(*args, **kwargs): ...
        @staticmethod
        def setXtraName(*args, **kwargs): ...
        @staticmethod
        def setDefaultTwistPoses(*args, **kwargs): ...
        @staticmethod
        def getPelvisVal(*args, **kwargs): ...
        @staticmethod
        def setSlidingKey(*args, **kwargs): ...
        @staticmethod
        def getCopyCollection(*args, **kwargs): ...
        @staticmethod
        def setPosSubAnim(*args, **kwargs): ...
        @staticmethod
        def getLayerActive(*args, **kwargs): ...
        @staticmethod
        def getMultipleFSParams(*args, **kwargs): ...
        @staticmethod
        def loadFigNoTwists(*args, **kwargs): ...
        @staticmethod
        def setEulerActive(*args, **kwargs): ...
        @staticmethod
        def setSnapKey(*args, **kwargs): ...
        @staticmethod
        def getIdLink(*args, **kwargs): ...
        @staticmethod
        def pasteBipTrack(*args, **kwargs): ...
        @staticmethod
        def deleteAllCopies(*args, **kwargs): ...
        @staticmethod
        def getCurrentClip(*args, **kwargs): ...
        @staticmethod
        def setRetargetRefBip(*args, **kwargs): ...
        @staticmethod
        def doSetMultipleKeysDlg(*args, **kwargs): ...
        @staticmethod
        def loadBipedBaseAnimationLayer(*args, **kwargs): ...
        @staticmethod
        def deselectKeys(*args, **kwargs): ...
        @staticmethod
        def setTwistPoseName(*args, **kwargs): ...
        @staticmethod
        def getFingerVal(*args, **kwargs): ...
        @staticmethod
        def setFreeKey(*args, **kwargs): ...
        @staticmethod
        def createCopyCollection(*args, **kwargs): ...
        @staticmethod
        def setRotSubAnim(*args, **kwargs): ...
        @staticmethod
        def setLayerActive(*args, **kwargs): ...
        @staticmethod
        def newFootprintKeys(*args, **kwargs): ...
        @staticmethod
        def loadFigJustTwists(*args, **kwargs): ...
        @staticmethod
        def setQuaternionActive(*args, **kwargs): ...
        @staticmethod
        def zeroTwist(*args, **kwargs): ...
        @staticmethod
        def getRotParentNode(*args, **kwargs): ...
        @staticmethod
        def pastePostureToXtras(*args, **kwargs): ...
        @staticmethod
        def numCopies(*args, **kwargs): ...
        @staticmethod
        def numPrefClips(*args, **kwargs): ...
        @staticmethod
        def RetargetToBaseLayer(*args, **kwargs): ...
        @staticmethod
        def convertToFreeForm(*args, **kwargs): ...
        @staticmethod
        def loadMocapFile(*args, **kwargs): ...
        @staticmethod
        def moveKeys(*args, **kwargs): ...
        @staticmethod
        def setTwistPoseTwist(*args, **kwargs): ...
        @staticmethod
        def getHorizontalControl(*args, **kwargs): ...
        @staticmethod
        def resetAllLimbKeys(*args, **kwargs): ...
        @staticmethod
        def deleteCopyCollection(*args, **kwargs): ...
        @staticmethod
        def setScaleSubAnim(*args, **kwargs): ...
        @staticmethod
        def getLayerName(*args, **kwargs): ...
        @staticmethod
        def getNode(*args, **kwargs): ...
        @staticmethod
        def saveBipFileSegment(*args, **kwargs): ...
        @staticmethod
        def fsAddSide(*args, **kwargs): ...
        @staticmethod
        def setEulerOrder(*args, **kwargs): ...
        @staticmethod
        def zeroAll(*args, **kwargs): ...
        @staticmethod
        def getPosParentNode(*args, **kwargs): ...
        @staticmethod
        def pasteTrackToXtras(*args, **kwargs): ...
        @staticmethod
        def deleteCopy(*args, **kwargs): ...
        @staticmethod
        def getPrefClip(*args, **kwargs): ...
        @staticmethod
        def RetargetToReferenceBiped(*args, **kwargs): ...
        @staticmethod
        def convertToFootSteps(*args, **kwargs): ...
        @staticmethod
        def adjustTalentPose(*args, **kwargs): ...
        @staticmethod
        def displayPrefsDlg(*args, **kwargs): ...
        @staticmethod
        def setTwistPoseBias(*args, **kwargs): ...
        @staticmethod
        def getVerticalControl(*args, **kwargs): ...
        @staticmethod
        def collapseMoveAllMode(*args, **kwargs): ...
        @staticmethod
        def deleteAllCopyCollections(*args, **kwargs): ...
        @staticmethod
        def collapseAllPosSubAnims(*args, **kwargs): ...
        @staticmethod
        def setLayerName(*args, **kwargs): ...
        @staticmethod
        def maxNumNodes(*args, **kwargs): ...
        @staticmethod
        def saveBipFile(*args, **kwargs): ...
        @staticmethod
        def createXtra(*args, **kwargs): ...
        @staticmethod
        def smoothTwist(*args, **kwargs): ...
        @staticmethod
        def getParentNodeRot(*args, **kwargs): ...
        @staticmethod
        def setCurrentCopyCollection(*args, **kwargs): ...
        @staticmethod
        def getCopyName(*args, **kwargs): ...
        @staticmethod
        def getPrefClipProb(*args, **kwargs): ...
        @staticmethod
        def unifyMotion(*args, **kwargs): ...
        @staticmethod
        def saveTalentFigFile(*args, **kwargs): ...
        @staticmethod
        def loadBipFileDlg(*args, **kwargs): ...
        @staticmethod
        def getTwistPoseName(*args, **kwargs): ...
        @staticmethod
        def getTurnControl(*args, **kwargs): ...
        @staticmethod
        def bendFootprints(*args, **kwargs): ...
        @staticmethod
        def copyBipPosture(*args, **kwargs): ...
        @staticmethod
        def collapseAllRotSubAnims(*args, **kwargs): ...
        @staticmethod
        def getCurrentLayer(*args, **kwargs): ...
        @staticmethod
        def maxNumLinks(*args, **kwargs): ...
        @staticmethod
        def saveFigFile(*args, **kwargs): ...
        @staticmethod
        def getKey(*args, **kwargs): ...
        ...

    class Sphere(runtime.GeometryClass):
        radius: float
        ...

    class TriMesh(Value):
        def selectedFaces(self) -> runtime.FaceSelection: ...
        ...

    class Box3: ...
    class Material: ...
    class setPropertyController(Primitive):
        def __new__(cls, contrller, target_name:str, new_controller) -> None: ...
    class SetCommandPanelTaskMode(Primitive):
        def __new__(cls, name: runtime.Name) -> None:
            """ name
            - create
            - modify
            - hierarchy 
            - motion 
            - display 
            - utility 
            """
            ...
        ...
    # class GetDir(Primitive):
    #     """
    #     :arg name:
    #     - #userMacros
    #     """
    #     def __new__(cls, name: runtime.Name) -> str:
    #         ...
    #     ...
    class getINISetting(Primitive):
        """[api](https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=GUID-CF408D64-D4E2-4C39-90DB-62E525D7B45A)
        
        :arg file_name: "c:/temp/test.ini"
        :arg section: "Directories"
        :arg key: "Scenes"
        """
        def __new__(cls, file_name: str, section:str, key:str, defaultValue: str="") -> str:
            ...
    class Point3(Value):
        """[x, y, z]

        [2022 api link](https://help.autodesk.com/view/MAXDEV/2022/ENU/?guid=GUID-1564BD35-50EA-4140-9150-1AECC89F713C)
        """
        x: int
        y: int
        z: int
        def __init__(self, *args, **kwargs) -> None: ...
        ...

    class Color(mxs.Color):
        def __init__(self, *args, **kwargs) -> None: ...

    class Biped(mxs.Biped): ...

    class LayerManager(mxs.LayerManager):
        @staticmethod
        def getLayerFromName(*args, **kwargs): ...
        ...
    class Generic(Value): ...

    class getnumtverts(Generic):
        """-> int"""

        def __new__(cls, node) -> int: ...
    class sort(Generic):
        """:arg items: iterable"""

        def __new__(cls, items:Iterable[_T]) -> Iterable[_T]: ...

    subObjectLevel: int

    class convertToMesh(NodeGeneric):
        def __new__(cls, node) -> None: ...

    class Skin(runtime.modifier):
        always_deform: bool
        enabledInViews: bool
        enable: bool

    class meshop(StructDef):
        @staticmethod
        def getNumVerts(*args, **kwargs) -> int:
            """ 버텍스"""
            ...
        @staticmethod
        def getNumMapFaces(*args, **kwargs) -> int:
            """getNumMapFaces <Mesh mesh> <Integer mapChannel>
            -> integer"""
            ...
        @staticmethod
        def getMapSupport(*args, **kwargs) -> bool:
            """getMapSupport <Mesh mesh> <Integer mapChannel>"""
            ...

        @staticmethod
        def setMapSupport(*args, **kwargs) -> bool:
            """setMapSupport <Mesh mesh> <Integer mapChannel> <Boolean support>"""
            ...

        @staticmethod
        def setNumMaps(*args, **kwargs) -> None:
            """meshop.setNumMaps <Mesh mesh> <int count> keep:<bool1ean=false>"""
            ...

        @staticmethod
        def getNumMaps(Any) -> int:
            """-> int(카운트를 반환)
            setNumMaps <Mesh mesh> <int count> keep:<bool1ean=false>"""
            ...

        @staticmethod
        def setNumMapVerts(*args, **kwargs) -> None:
            """setNumMapVerts <Mesh mesh> <Integer mapChannel> <Integer count> keep:<boolean=FALSE>"""
            ...

        @staticmethod
        def getMapVertsUsingMapFace(*args, **kwargs) -> runtime.BitArray:
            """meshop.getMapVertsUsingMapFace <Mesh mesh> <int mapChannel> <mapFacelist>"""
            ...

        @staticmethod
        def getFaceCenter(*args, **kwargs) -> runtime.Point3:
            """<point3>meshop.getFaceCenter <Mesh mesh> <int faceIndex> node:<node=unsupplied>"""
            ...
    class getNumFaces(Generic):
        def __new__(cls, node) -> int: ...
    class polyop(StructDef):
        """ """
        @staticmethod
        def getNumVDataChannels(*args, **kwargs):...
        @staticmethod
        def getNumMaps(*args, **kwargs):...
        @staticmethod
        def weldEdgesByThreshold(*args, **kwargs):...
        @staticmethod
        def createPolygon(*args, **kwargs):...
        @staticmethod
        def createVert(*args, **kwargs):...
        @staticmethod
        def collapseDeadStructs(*args, **kwargs):...
        @staticmethod
        def getVertsByMatId(*args, **kwargs):...
        @staticmethod
        def setFaceFlags(*args, **kwargs):...
        @staticmethod
        def setEDataChannelSupport(*args, **kwargs):...
        @staticmethod
        def setMapFace(*args, **kwargs):...
        @staticmethod
        def capHolesByEdge(*args, **kwargs):...
        @staticmethod
        def cutFace(*args, **kwargs):...
        @staticmethod
        def makeVertsPlanar(*args, **kwargs):...
        @staticmethod
        def inSlicePlaneMode(*args, **kwargs):...
        @staticmethod
        def getFacesEdges(*args, **kwargs):...
        @staticmethod
        def getFacesUsingVert(*args, **kwargs):...
        @staticmethod
        def getVertsByFlag(*args, **kwargs):...
        @staticmethod
        def setVDataChannelSupport(*args, **kwargs):...
        @staticmethod
        def setMapSupport(*args, **kwargs):...
        @staticmethod
        def weldEdges(*args, **kwargs):...
        @staticmethod
        def unHideAllFaces(*args, **kwargs):...
        @staticmethod
        def unHideAllVerts(*args, **kwargs):...
        @staticmethod
        def attach(*args, **kwargs):...
        @staticmethod
        def getBorderFromEdge(*args, **kwargs):...
        @staticmethod
        def getDeadVerts(*args, **kwargs):...
        @staticmethod
        def getNumVerts(*args, **kwargs):...
        @staticmethod
        def getEDataChannelSupport(*args, **kwargs):...
        @staticmethod
        def getMapFace(*args, **kwargs):...
        @staticmethod
        def makeEdgesPlanar(*args, **kwargs):...
        @staticmethod
        def capHolesByFace(*args, **kwargs):...
        @staticmethod
        def moveVertsToPlane(*args, **kwargs):...
        @staticmethod
        def getVert(*args, **kwargs):...
        @staticmethod
        def getFaceDeg(*args, **kwargs):...
        @staticmethod
        def getVertsUsingEdge(*args, **kwargs):...
        @staticmethod
        def getVertFlags(*args, **kwargs):...
        @staticmethod
        def getVDataChannelSupport(*args, **kwargs):...
        @staticmethod
        def getMapSupport(*args, **kwargs):...
        @staticmethod
        def divideEdge(*args, **kwargs):...
        @staticmethod
        def setFaceSmoothGroup(*args, **kwargs):...
        @staticmethod
        def autosmooth(*args, **kwargs):...
        @staticmethod
        def breakVerts(*args, **kwargs):...
        @staticmethod
        def deleteIsoVerts(*args, **kwargs):...
        @staticmethod
        def getEdgeVerts(*args, **kwargs):...
        @staticmethod
        def getDeadEdges(*args, **kwargs):...
        @staticmethod
        def getNumEdges(*args, **kwargs):...
        @staticmethod
        def getEDataValue(*args, **kwargs):...
        @staticmethod
        def defaultMapFaces(*args, **kwargs):...
        @staticmethod
        def moveEdgesToPlane(*args, **kwargs):...
        @staticmethod
        def makeFacesPlanar(*args, **kwargs):...
        @staticmethod
        def chamferVerts(*args, **kwargs):...
        @staticmethod
        def getVerts(*args, **kwargs):...
        @staticmethod
        def getFacesUsingEdge(*args, **kwargs):...
        @staticmethod
        def setVertFlags(*args, **kwargs):...
        @staticmethod
        def getVDataValue(*args, **kwargs):...
        @staticmethod
        def setNumMapVerts(*args, **kwargs):...
        @staticmethod
        def collapseEdges(*args, **kwargs):...
        @staticmethod
        def getFaceSmoothGroup(*args, **kwargs):...
        @staticmethod
        def collapseVerts(*args, **kwargs):...
        @staticmethod
        def forceSubdivision(*args, **kwargs):...
        @staticmethod
        def getEdgeFaces(*args, **kwargs):...
        @staticmethod
        def getDeadFaces(*args, **kwargs):...
        @staticmethod
        def getNumFaces(*args, **kwargs):...
        @staticmethod
        def setEDataValue(*args, **kwargs):...
        @staticmethod
        def applyUVWMap(*args, **kwargs):...
        @staticmethod
        def createShape(*args, **kwargs):...
        @staticmethod
        def moveFacesToPlane(*args, **kwargs):...
        @staticmethod
        def getFaceMatID(*args, **kwargs):...
        @staticmethod
        def setVert(*args, **kwargs):...
        @staticmethod
        def getSafeFaceCenter(*args, **kwargs):...
        @staticmethod
        def getVertsUsingFace(*args, **kwargs):...
        @staticmethod
        def getEdgesByFlag(*args, **kwargs):...
        @staticmethod
        def getVertSelection(*args, **kwargs):...
        @staticmethod
        def checkTriangulation(*args, **kwargs):...
        @staticmethod
        def setVDataValue(*args, **kwargs):...
        @staticmethod
        def getNumMapVerts(*args, **kwargs):...
        @staticmethod
        def splitEdges(*args, **kwargs):...
        @staticmethod
        def divideFace(*args, **kwargs):...
        @staticmethod
        def meshSmoothByVert(*args, **kwargs):...
        @staticmethod
        def propagateFlags(*args, **kwargs):...
        @staticmethod
        def getEdgesVerts(*args, **kwargs):...
        @staticmethod
        def getHasDeadStructs(*args, **kwargs):...
        @staticmethod
        def getHiddenVerts(*args, **kwargs):...
        @staticmethod
        def freeEData(*args, **kwargs):...
        @staticmethod
        def getVertsByColor(*args, **kwargs):...
        @staticmethod
        def getEdgeVis(*args, **kwargs):...
        @staticmethod
        def extrudeFaces(*args, **kwargs):...
        @staticmethod
        def getFacesMatID(*args, **kwargs):...
        @staticmethod
        def moveVert(*args, **kwargs):...
        @staticmethod
        def getFaceNormal(*args, **kwargs):...
        @staticmethod
        def getEdgesUsingFace(*args, **kwargs):...
        @staticmethod
        def getEdgeFlags(*args, **kwargs):...
        @staticmethod
        def setVertSelection(*args, **kwargs):...
        @staticmethod
        def freeVData(*args, **kwargs):...
        @staticmethod
        def setNumMapFaces(*args, **kwargs):...
        @staticmethod
        def meshSmoothByEdge(*args, **kwargs):...
        @staticmethod
        def slice(*args, **kwargs):...
        @staticmethod
        def collapseFaces(*args, **kwargs):...
        @staticmethod
        def tessellateByVert(*args, **kwargs):...
        @staticmethod
        def fillInMesh(*args, **kwargs):...
        @staticmethod
        def getEdgesFaces(*args, **kwargs):...
        @staticmethod
        def isFaceDead(*args, **kwargs):...
        @staticmethod
        def setHiddenVerts(*args, **kwargs):...
        @staticmethod
        def resetEData(*args, **kwargs):...
        @staticmethod
        def setFaceColor(*args, **kwargs):...
        @staticmethod
        def setEdgeVis(*args, **kwargs):...
        @staticmethod
        def bevelFaces(*args, **kwargs):...
        @staticmethod
        def setFaceMatID(*args, **kwargs):...
        @staticmethod
        def deleteVerts(*args, **kwargs):...
        @staticmethod
        def getFaceArea(*args, **kwargs):...
        @staticmethod
        def getElementsUsingFace(*args, **kwargs):...
        @staticmethod
        def setEdgeFlags(*args, **kwargs):...
        @staticmethod
        def getEdgeSelection(*args, **kwargs):...
        @staticmethod
        def resetVData(*args, **kwargs):...
        @staticmethod
        def getNumMapFaces(*args, **kwargs):...
        @staticmethod
        def tessellateByEdge(*args, **kwargs):...
        @staticmethod
        def meshSmoothByFace(*args, **kwargs):...
        @staticmethod
        def detachVerts(*args, **kwargs):...
        @staticmethod
        def resetSlicePlane(*args, **kwargs):...
        @staticmethod
        def isEdgeDead(*args, **kwargs):...
        @staticmethod
        def getHiddenFaces(*args, **kwargs):...
        @staticmethod
        def setVertColor(*args, **kwargs):...
        @staticmethod
        def chamferEdges(*args, **kwargs):...
        @staticmethod
        def deleteEdges(*args, **kwargs):...
        @staticmethod
        def retriangulate(*args, **kwargs):...
        @staticmethod
        def deleteFaces(*args, **kwargs):...
        @staticmethod
        def weldVertsByThreshold(*args, **kwargs):...
        @staticmethod
        def getFacesByMatId(*args, **kwargs):...
        @staticmethod
        def getVertsUsedOnlyByFaces(*args, **kwargs):...
        @staticmethod
        def getFacesByFlag(*args, **kwargs):...
        @staticmethod
        def setEdgeSelection(*args, **kwargs):...
        @staticmethod
        def setNumEDataChannels(*args, **kwargs):...
        @staticmethod
        def setMapVert(*args, **kwargs):...
        @staticmethod
        def detachEdges(*args, **kwargs):...
        @staticmethod
        def tessellateByFace(*args, **kwargs):...
        @staticmethod
        def cutVert(*args, **kwargs):...
        @staticmethod
        def getSlicePlane(*args, **kwargs):...
        @staticmethod
        def getFaceEdges(*args, **kwargs):...
        @staticmethod
        def isVertDead(*args, **kwargs):...
        @staticmethod
        def setHiddenFaces(*args, **kwargs):...
        @staticmethod
        def setNumVDataChannels(*args, **kwargs):...
        @staticmethod
        def setNumMaps(*args, **kwargs):...
        @staticmethod
        def createEdge(*args, **kwargs):...
        @staticmethod
        def setDiagonal(*args, **kwargs):...
        @staticmethod
        def flipNormals(*args, **kwargs):...
        @staticmethod
        def weldVerts(*args, **kwargs):...
        @staticmethod
        def getAllFaces(*args, **kwargs):...
        @staticmethod
        def isMeshFilledIn(*args, **kwargs):...
        @staticmethod
        def getFaceFlags(*args, **kwargs):...
        @staticmethod
        def getFaceSelection(*args, **kwargs):...
        @staticmethod
        def getNumEDataChannels(*args, **kwargs):...
        @staticmethod
        def getMapVert(*args, **kwargs):...
        @staticmethod
        def cutEdge(*args, **kwargs):...
        @staticmethod
        def detachFaces(*args, **kwargs):...
        @staticmethod
        def capHolesByVert(*args, **kwargs):...
        @staticmethod
        def setSlicePlane(*args, **kwargs):...
        @staticmethod
        def getFacesVerts(*args, **kwargs):...
        @staticmethod
        def getEdgesUsingVert(*args, **kwargs):...
        @staticmethod
        def getOpenEdges(*args, **kwargs):...
        @staticmethod
        def getFaceCenter(*args, **kwargs) -> runtime.Point3:
            """<point3>polyop.getFaceCenter <Mesh mesh> <int faceIndex> node:<node=unsupplied>"""
            ...

        @staticmethod
        def getFaceVerts(*args, **kwargs) -> runtime.BitArray:
            """<bitArray>polyop.getFaceVerts <Mesh mesh> <int faceIndex>"""
            ...

        @staticmethod
        def setFaceSelection(*args, **kwargs) -> None: ...
        @staticmethod
        def getFacesUsingMapFace(*args, **kwargs) -> runtime.BitArray: ...


    class BoneSys(runtime.Interface):
        @staticmethod
        def createBone(startPos:runtime.Point3,
                       endPos: runtime.Point3,
                       zAxis: runtime.Point3) -> runtime.Bone: ...
    class controller: ...
    class Quat: ...

    class Matrix3(Value):
        """
        [2022 api link](https://help.autodesk.com/view/MAXDEV/2022/ENU/?guid=GUID-D77C780A-4E8A-4528-949F-CC09AAE048DA)
        """
        rotation: runtime.Quat
        """ 회전값 """
        position: runtime.Point3
        row1: runtime.Point3
        row2: runtime.Point3
        row3: runtime.Point3
        row4: runtime.Point3
        translation: runtime.Point3
        @overload
        def __init__(self, flag: Literal[0, 1]) -> None: ...

        @overload
        def __init__(self,
                     row1:runtime.Point3,
                     row2:runtime.Point3,
                     row3:runtime.Point3,
                     row4:runtime.Point3,
                     ) -> None: ...
        ...
        def __mul__(self, other: runtime.Matrix3) -> runtime.Matrix3: ...
        def __rmul__(self, other: runtime.Matrix3) -> runtime.Matrix3: ...

    class modifier(MAXWrapper):
        """ """
        name: str
        """ 모디파이어 이름 """

        ...

    class Skin_Wrap(modifier):
        class meshDeformOps():
            @staticmethod
            def ConvertToSkin(*args, **kwargs) -> None: ...
        engine: int
        falloff: float
        weightAllVerts: bool
        blend: bool
        meshList: runtime.Array
        ...
    class Unwrap_UVW(modifier):
        """https://help.autodesk.com/view/MAXDEV/2023/ENU/?guid=GUID-17D700DC-1FDC-4713-8041-D9E3C3EB4789"""
        class unwrap:
            def __init__(self) -> None: ...
            @classmethod
            def setMapChannel(cls, index: int) -> None: ...
        class unwrap2:
            @staticmethod
            def flattenMapNoParams() -> None: ...
        def __init__(self) -> None: ...
        def setFaceVertex(
            self,
            point3: runtime.Point3,
            face_index: int,
            vertex_index: int,
            sel: bool,
        ) -> None:
            """
            setFaceVertex <point3>pos <integer>faceIndex <integer>ithVertex <boolean>sel
            """
            ...

        def numberPointsInFace(self, index: int) -> int:
            """<integer><Unwrap_UVW>.numberPointsInFace <integer>index
                    면에 포함된 정점 수를 검색합니다.

            면은 Unwrap이 작업 중인 토폴로지 유형에 따라 3~N개의 점을 포함할 수 있습니다. 트라이 메시의 경우 이는 항상 3입니다. 패치의 경우 3 또는 4일 수 있습니다. 다각형의 경우 이는 3 이상이 될 수 있습니다. Unwrap은 세 가지 객체 유형을 모두 하나의 일반 형식으로 추상화합니다.

            <integer> index- 검사 중인 얼굴의 인덱스입니다.
            numberPointsInFace(1) -> 0
            """
            ...

        def getVertexIndexFromFace(
            self, fase_index: int, target_index: int
        ) -> int:
            """<integer><Unwrap_UVW>.getVertexIndexFromFace <integer>faceIndex <integer>ithVertex
            - ithVertex: faceIndex에서 몇 번째 정점을 찾을지 지정
            - 면에서 정점의 인덱스를 검색
            - 면 인덱스와 검사하려는 i번째 정점을 제공
            """
            ...

        def getVertexGeomIndexFromFace(
            self, face_index: int, target_index: int
        ) -> int:
            """<integer><Unwrap_UVW>.getVertexGeomIndexFromFace <integer>faceIndex <integer>ithVertex
            - ithVertex: faceIndex에서 몇 번째 정점을 찾을지 지정
            - 면에서 **메쉬**의 정점의 인덱스를 검색

            """
            ...
        def flattenMap(self, angleThreshold, normalList, spacing, normalize, layOutType, rotateClusters, fillHoles) -> None:
            """flattenMap <float>angleThreshold <point3 array>normalList <float>spacing <boolean>normalize <integer>layOutType <boolean>rotateClusters <boolean>fillHoles
            - 매핑 평탄화 대화상자를 사용하지 않고 제공된 파라미터에 따라 UVW 좌표를 평탄화합니다.
            - 이 메서드는 동일한 기능을 MAXScript에 직접 노출하며 UVW 플로터 편집을 열지 않아도 됩니다.
            """
            ...

    @staticmethod
    def maxVersion() -> list[int| str]:
        """:return: #(25000, 62, 0, 25, 2, 2, 3312, 2023, ".2.2 Update")
            - 25000: 릴리스 번호
            - 62: API버전
            - 0: SDK 개정판
            - 25: 주요 버전
            - 업데이트 버전
            - 핫픽스 번호
            - 빌드 번호
            - 연도
            - 버전 설명
        :rtype: list[int]
        [wep api](https://help.autodesk.com/view/MAXDEV/2024/ENU/?guid=GUID-53F8D6CE-A5A6-4353-BE48-4298BBE107DE)
        """;...

    @staticmethod
    def addModifier(*args, **kwargs) -> None: ...
    @staticmethod
    def getSubAnim(*args, **kwargs) -> None: ...
    @staticmethod
    def select(*args, **kwargs) -> None: ...
    @staticmethod
    def importFile(*args, **kwargs) -> None: ...
    @staticmethod
    def FBXExporterSetParam(*args, **kwargs) -> None: ...
    @staticmethod
    def execute(*args, **kwargs) -> None: ...
    @staticmethod
    def doesFileExist(*args, **kwargs) -> bool: ...
    @staticmethod
    def rotateZ(*args, **kwargs) -> Matrix3: ...
    @staticmethod
    def snapshot(Node: runtime.GeometryClass) -> runtime.Editable_mesh: ...
    @staticmethod
    def redrawViews(): ...
    @staticmethod
    def inverse(matrix3: Matrix3) -> Matrix3: ...
    @staticmethod
    def AttachObjects(
        pNode: runtime.node, node: runtime.node, move=True
    ): ...
    @staticmethod
    def classOf(obj: Value): ...
    @staticmethod
    def setSelectionLevel(obj: runtime.node, level: Name):
        """
        :type level: literal[#object, #vertex, #edge, #face]
        """